### ISSUE TITLE
About training images in SF-XL

### ISSUE THREAD

**Issue by ShihaoShao-GH** [gmberton/EigenPlaces#1]
Hi, I just downloaded SF-XL, and used this repo to train on them. Because I was doubt if there was a mistake about downloading. I would like to ensure that if this image number seems correct to you?

> 2023-10-09 00:46:28   Searching images in /data1/shaoshihao/sf_xl/train with glob()
> 2023-10-09 00:47:11   Found 3431092 images

Thanks in advance!

**Comment by gmberton** [comment]
Yes, the number is correct.
Those 3.4M images are 360° panoramas of resolution 3328 x 512 pixels. During training, a panorama is loaded, and from it an image is cropped with the needed orientation and with resolution 512 x 512.
Note that because panoramas are quite heavy, data loading could be the bottleneck so it is advised to keep those images on a fast SSD.
